pipeline {
    agent {
        node {
            label 'Agent-1'
        }
    }
    environment {
        Greeting = 'Arun'
        //  packageVersion = ''
    }
    options {
        ansiColor('xterm')
        timeout(time:1, unit:'HOURS' )
    }
    parameters {
        string (name:'version', defaultValue: '', description:'what is Application artifact Version ?')
        string (name:'environment', defaultValue: '', description:'What is the environment ?')
    }
    stages {
        stage('Print Version') {
            steps {
                sh """
                    echo "version : ${params.version}"
                    echo "environment : ${params.environment}"
                """
            }
        }
        stage('Init') {
            steps {
                sh """
                    pwd
                    cd catalogue-deploy/terraform/
                    pwd
                    terraform init --backend-config=${params.environment}/backend.tf -reconfigure
                """
            }
        }
        // stage('Plan') {
        //     steps {
        //         sh """
        //             pwd
        //             cd catalogue-deploy/terraform/
        //             pwd
        //             terraform init --backend-config=${params.environment}/backend.tf -reconfigure
        //         """
        //     }
        // }
    }
    post {
        always {
            echo "always runs this"
        }
    }
}