// we need to do infra creation until 01-vpn,02-sg,03-vppn.04-databases and 05-app-alb create via manually to work user
// add roboshop-dev-vpn to agent instance to run user

pipeline {
    agent {
        node {
            label 'Agent-1'
        }
    }
    environment {
        Greeting = 'Arun'
        //  packageVersion = ''
    }
    options {
        ansiColor('xterm')
        timeout(time:1, unit:'HOURS' )
    }
    parameters {
        string (name:'version', defaultValue: '', description:'what is Application artifact Version ?')
        string (name:'environment', defaultValue: '', description:'What is the environment ?')
        string(name: 'action', defaultValue: 'Apply')
        // choice (name: 'action', choices: ['Apply', 'Destroy'])
    }
    stages {
        stage('Print Version') {
            steps {
                sh """
                    echo "version : ${params.version}"
                    echo "environment : ${params.environment}"
                """
            }
        }
        stage('Init') {
            steps {
                sh """
                    pwd
                    cd user-deploy/terraform/
                    pwd
                    terraform init --backend-config=${params.environment}/backend.tf -reconfigure
                """
            }
        }
        stage('Plan') {
            steps {
                sh """
                    cd user-deploy/terraform/
                    terraform plan -var-file=${params.environment}/${params.environment}.tfvars -var="app_version=${params.version}"
                """
            }
        }
        //we need to attach roboshop-dev-vpn sg to agent-1 ec2 sg group to work 
        stage('Apply') {
            when {
                expression {
                    params.action == 'Apply'
                }
            }
            steps {
                sh """
                    cd user-deploy/terraform/
                    terraform apply -var-file=${params.environment}/${params.environment}.tfvars -var="app_version=${params.version}" -auto-approve
                """
            }
        }
        stage('Destroy') {
            when {
                expression {
                    params.action == 'Destroy'
                }
            }
            steps {
                sh """
                    cd user-deploy/terraform/
                    terraform destroy -var-file=${params.environment}/${params.environment}.tfvars -var="app_version=${params.version}" -auto-approve
                """
            }
        }
        
    }
    post {
        always {
            echo "always runs this"
            deleteDir()
        }
    }
}